{% set name = "pyod" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e05b7a457ac9bd8b0cc41754fdafe3aefcc1f61270f33d38f43112676d9db2b8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - joblib
    - matplotlib-base
    - numba >=0.51
    - numpy >=1.19
    - scikit-learn >=0.20.0
    - scipy >=1.5.1
    - six
    - statsmodels

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyod
    - pyod.models
    - pyod.utils

about:
  home: https://github.com/yzhao062/pyod
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python Toolkit for Scalable Outlier Detection (Anomaly Detection)
  doc_url: https://pyod.readthedocs.io

extra:
  recipe-maintainers:
    - yzhao062
    - apcamargo
